language: elixir
elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.4
otp_release:
  - 17.4
  - 18.0
  - 18.1
  - 18.2
  - 18.3
matrix:
  exclude:
    - elixir: 1.0.5
      otp_release: 18.0
    - elixir: 1.0.5
      otp_release: 18.1
    - elixir: 1.0.5
      otp_release: 18.2
    - elixir: 1.0.5
      otp_release: 18.3
    - elixir: 1.1.1
      otp_release: 17.4
    - elixir: 1.2.4
      otp_release: 17.4
cache:
  directories:
    - _build
    - deps
