language: elixir
elixir:
  - 1.1.1
  - 1.2.6
  - 1.3.4
otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 18.3
  - 19.0
  - 19.1
matrix:
  exclude:
    - elixir: 1.1.1
      otp_release: 19.0
    - elixir: 1.1.1
      otp_release: 19.1
cache:
  directories:
    - _build
    - deps
