language: elixir
elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.6
  - 1.3.4
  - 1.4.5
  - 1.5.2
otp_release:
  - 17.4
  - 18.3
  - 19.3
  - 20.1
matrix:
  exclude:
    - elixir: 1.0.5
      otp_release: 18.3
    - elixir: 1.0.5
      otp_release: 19.3
    - elixir: 1.0.5
      otp_release: 20.1
    - elixir: 1.1.1
      otp_release: 17.4
    - elixir: 1.1.1
      otp_release: 19.3
    - elixir: 1.1.1
      otp_release: 20.1
    - elixir: 1.2.6
      otp_release: 17.4
    - elixir: 1.2.6
      otp_release: 20.1
    - elixir: 1.3.4
      otp_release: 17.4
    - elixir: 1.3.4
      otp_release: 20.1
    - elixir: 1.4.5
      otp_release: 17.4
    - elixir: 1.5.2
      otp_release: 17.4
cache:
  directories:
    - _build
    - deps
